import {
  Listing,
  CenterPoint,
  PropertyTypeConfig,
  PipelineStatusConfig,
} from "@/types/hunting";

export const propertyTypes: PropertyTypeConfig[] = [
  { id: "condo", name: "Condos", icon: "building-2", color: "#3b82f6" },
  { id: "apartment", name: "Apartments", icon: "home", color: "#8b5cf6" },
  { id: "dorm", name: "Dorms & Studios", icon: "graduation-cap", color: "#f97316" },
  { id: "house", name: "Houses & Townhomes", icon: "building", color: "#10b981" },
];

export const pipelineStatuses: PipelineStatusConfig[] = [
  {
    id: "interested",
    name: "Interested",
    color: "#a855f7",
    badgeClass: "bg-purple-500/15 text-purple-700 dark:text-purple-300 border-purple-300/40",
  },
  {
    id: "viewing_scheduled",
    name: "Viewing Scheduled",
    color: "#3b82f6",
    badgeClass: "bg-blue-500/15 text-blue-700 dark:text-blue-300 border-blue-300/40",
  },
  {
    id: "viewed",
    name: "Viewed",
    color: "#64748b",
    badgeClass: "bg-slate-500/15 text-slate-700 dark:text-slate-300 border-slate-300/40",
  },
  {
    id: "negotiating",
    name: "Negotiating",
    color: "#f59e0b",
    badgeClass: "bg-amber-500/15 text-amber-700 dark:text-amber-300 border-amber-300/40",
  },
  {
    id: "decided",
    name: "Decided",
    color: "#10b981",
    badgeClass: "bg-emerald-500/15 text-emerald-700 dark:text-emerald-300 border-emerald-300/40",
  },
  {
    id: "rejected",
    name: "Rejected",
    color: "#f43f5e",
    badgeClass: "bg-rose-500/15 text-rose-700 dark:text-rose-300 border-rose-300/40",
  },
];

export const initialCenterPoints: CenterPoint[] = [
  {
    id: "cp-workplace",
    name: "Workplace (Siam / CentralWorld)",
    lat: 13.7462,
    lng: 100.5347,
    category: "workplace",
    icon: "briefcase",
    color: "#ec4899",
  },
  {
    id: "cp-transit",
    name: "BTS Asok Interchange",
    lat: 13.7369,
    lng: 100.5604,
    category: "transit",
    icon: "train",
    color: "#3b82f6",
  },
  {
    id: "cp-university",
    name: "University (Chulalongkorn)",
    lat: 13.7382,
    lng: 100.5323,
    category: "university",
    icon: "graduation-cap",
    color: "#8b5cf6",
  },
  {
    id: "cp-cbd",
    name: "Silom / Sathorn Office",
    lat: 13.7278,
    lng: 100.5317,
    category: "workplace",
    icon: "building-2",
    color: "#06b6d4",
  },
];

export const initialListings: Listing[] = [
  {
    id: "condo-1",
    name: "Life Asoke Hype",
    address: "333 Asoke-Din Daeng Rd, Makkasan, Ratchathewi, Bangkok 10400",
    lat: 13.7554,
    lng: 100.5658,
    type: "condo",
    size_sqm: 32,
    floor: 18,
    view: "Unblocked City & Sunset view",
    source_url: "https://www.ddproperty.com/en/property/life-asoke-hype",
    contact_phone: "089-123-4567",
    contact_line: "@asoke_agent",
    status: "negotiating",
    is_favorite: true,
    created_at: "2025-02-15T09:00:00.000Z",
    notes: "Super convenient to MRT Rama 9 and Airport Rail Link. High floor, very breezy. Owner willing to throw in new Samsung Smart TV.",
    amenities: {
      elevator: true,
      gym: true,
      pool: true,
      parking: true,
      cctv: true,
      keycard: true,
    },
    photos: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&auto=format&fit=crop&q=80",
    ],
    price_history: [
      {
        id: "ph-1a",
        listing_id: "condo-1",
        rent: 18000,
        deposit: 36000,
        advance: 18000,
        common_fee: 0,
        parking_fee: 0,
        internet_fee: 0,
        water_type: "metered",
        water_rate: "18 ฿/unit",
        electric_type: "government",
        electric_rate: "MEA Official Rate (~4.4 ฿)",
        recorded_at: "2025-02-15T09:00:00.000Z",
        note: "Initial advertised rent on DDproperty",
      },
      {
        id: "ph-1b",
        listing_id: "condo-1",
        rent: 17000,
        deposit: 34000,
        advance: 17000,
        common_fee: 0,
        parking_fee: 0,
        internet_fee: 0,
        water_type: "metered",
        water_rate: "18 ฿/unit",
        electric_type: "government",
        electric_rate: "MEA Official Rate (~4.4 ฿)",
        recorded_at: "2025-02-22T14:30:00.000Z",
        note: "Negotiated down 1,000 ฿ for 1-year lease",
      },
    ],
    contract: {
      id: "ct-1",
      listing_id: "condo-1",
      start_date: "2025-04-01",
      end_date: "2026-03-31",
      duration_months: 12,
      deposit_refund_terms: "Full refund within 30 days after room inspection and utility clearance.",
      pet_allowed: false,
      smoking_allowed: false,
      guest_allowed: true,
      early_termination_penalty: "Deposit of 2 months forfeited upon early termination.",
      contract_file_url: "https://example.com/contracts/life-asoke-draft.pdf",
    },
    viewing_logs: [
      {
        id: "vl-1",
        listing_id: "condo-1",
        scheduled_at: "2025-02-20T14:00:00.000Z",
        notes: "Visited in afternoon. Good natural light, very quiet corridor. Aircon is cold, water heater in bathroom works well.",
        rating: 4.5,
        completed: true,
      },
    ],
  },
  {
    id: "condo-2",
    name: "Ideo Sukhumvit 93",
    address: "Sukhumvit Rd, Bang Chak, Phra Khanong, Bangkok 10260",
    lat: 13.6998,
    lng: 100.6053,
    type: "condo",
    size_sqm: 35,
    floor: 12,
    view: "Swimming pool view",
    source_url: "https://www.facebook.com/marketplace/item/ideosukhumvit93",
    contact_phone: "081-987-6543",
    contact_line: "somchai_condo",
    status: "viewing_scheduled",
    is_favorite: true,
    created_at: "2025-02-18T11:00:00.000Z",
    notes: "Right in front of BTS Bang Chak (15 meters via sheltered walkway). Has 7-Eleven and Starbucks in the project.",
    amenities: {
      elevator: true,
      gym: true,
      pool: true,
      parking: true,
      cctv: true,
      keycard: true,
    },
    photos: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=800&auto=format&fit=crop&q=80",
    ],
    price_history: [
      {
        id: "ph-2",
        listing_id: "condo-2",
        rent: 15500,
        deposit: 31000,
        advance: 15500,
        common_fee: 0,
        parking_fee: 0,
        internet_fee: 450,
        water_type: "metered",
        water_rate: "20 ฿/unit",
        electric_type: "government",
        electric_rate: "MEA Official Rate",
        recorded_at: "2025-02-18T11:00:00.000Z",
        note: "Owner post on Facebook Marketplace",
      },
    ],
    viewing_logs: [
      {
        id: "vl-2",
        listing_id: "condo-2",
        scheduled_at: "2025-03-02T10:30:00.000Z",
        notes: "Appointment confirmed with Khun Somchai. Meet at lobby tower B.",
        rating: 4.0,
        completed: false,
      },
    ],
  },
  {
    id: "condo-3",
    name: "Park Origin Phrom Phong",
    address: "24 Sukhumvit Rd, Khlong Tan, Khlong Toei, Bangkok 10110",
    lat: 13.7275,
    lng: 100.5672,
    type: "condo",
    size_sqm: 40,
    floor: 26,
    view: "High rise panoramic Benjakitti Park view",
    source_url: "https://www.livinginsider.com/livingdetail/park-origin-phrom-phong",
    contact_phone: "092-333-8899",
    contact_line: "agent_phromphong",
    status: "interested",
    is_favorite: false,
    created_at: "2025-02-10T15:00:00.000Z",
    notes: "Prime luxury location in EmDistrict. Shuttles to BTS Phrom Phong. Stunning rooftop infinity pool.",
    amenities: {
      elevator: true,
      gym: true,
      pool: true,
      parking: true,
      cctv: true,
      keycard: true,
    },
    photos: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&auto=format&fit=crop&q=80",
    ],
    price_history: [
      {
        id: "ph-3",
        listing_id: "condo-3",
        rent: 24000,
        deposit: 48000,
        advance: 24000,
        common_fee: 0,
        parking_fee: 0,
        internet_fee: 600,
        water_type: "metered",
        water_rate: "20 ฿/unit",
        electric_type: "government",
        electric_rate: "MEA Official Rate",
        recorded_at: "2025-02-10T15:00:00.000Z",
        note: "Asking price for high-floor corner unit",
      },
    ],
    viewing_logs: [],
  },
  {
    id: "condo-4",
    name: "Rhythm Phahon-Ari",
    address: "Phahonyothin Rd, Sam Sen Nai, Phaya Thai, Bangkok 10400",
    lat: 13.7845,
    lng: 100.5452,
    type: "condo",
    size_sqm: 45,
    floor: 15,
    view: "Ari residential green canopy view",
    source_url: "https://www.ddproperty.com/en/property/rhythm-ari",
    contact_phone: "084-555-1122",
    contact_line: "ari_living",
    status: "viewed",
    is_favorite: true,
    created_at: "2025-02-05T08:00:00.000Z",
    notes: "Ari neighbourhood has great food cafes and vibe. 7-min walk to BTS Ari. Big kitchen area with induction cooker.",
    amenities: {
      elevator: true,
      gym: true,
      pool: true,
      parking: true,
      cctv: true,
      keycard: true,
    },
    photos: [
      "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80",
    ],
    price_history: [
      {
        id: "ph-4",
        listing_id: "condo-4",
        rent: 19500,
        deposit: 39000,
        advance: 19500,
        common_fee: 0,
        parking_fee: 0,
        internet_fee: 500,
        water_type: "metered",
        water_rate: "18 ฿/unit",
        electric_type: "government",
        electric_rate: "MEA Official Rate",
        recorded_at: "2025-02-05T08:00:00.000Z",
      },
    ],
    viewing_logs: [
      {
        id: "vl-4",
        listing_id: "condo-4",
        scheduled_at: "2025-02-12T16:00:00.000Z",
        notes: "Very clean building. Friendly juristic office. Gym has squat rack. Only downside is evening traffic along Phahonyothin.",
        rating: 4.8,
        completed: true,
      },
    ],
  },
  {
    id: "apt-1",
    name: "Baan Siri Sathorn Residences",
    address: "Soi Sathon 1, Thung Maha Mek, Sathon, Bangkok 10120",
    lat: 13.7224,
    lng: 100.5436,
    type: "apartment",
    size_sqm: 55,
    floor: 4,
    view: "Lush garden courtyard",
    source_url: "https://www.renthub.in.th/baan-siri-sathorn",
    contact_phone: "02-287-9900",
    contact_line: "baansiri_sathorn",
    status: "decided",
    is_favorite: true,
    created_at: "2025-01-20T10:00:00.000Z",
    notes: "Spacious boutique apartment, pet friendly! Walking distance to MRT Lumphini and Lumphini Park. Negotiated free fiber internet.",
    amenities: {
      elevator: true,
      gym: true,
      pool: true,
      parking: true,
      cctv: true,
      keycard: true,
    },
    photos: [
      "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=800&auto=format&fit=crop&q=80",
    ],
    price_history: [
      {
        id: "ph-apt1-1",
        listing_id: "apt-1",
        rent: 23000,
        deposit: 46000,
        advance: 23000,
        common_fee: 1000,
        parking_fee: 0,
        internet_fee: 500,
        water_type: "flat",
        water_rate: "Fixed 250 ฿/month",
        electric_type: "metered",
        electric_rate: "7 ฿/unit",
        recorded_at: "2025-01-20T10:00:00.000Z",
        note: "Initial contract offer",
      },
      {
        id: "ph-apt1-2",
        listing_id: "apt-1",
        rent: 21500,
        deposit: 43000,
        advance: 21500,
        common_fee: 0,
        parking_fee: 0,
        internet_fee: 0,
        water_type: "flat",
        water_rate: "Fixed 250 ฿/month",
        electric_type: "metered",
        electric_rate: "7 ฿/unit",
        recorded_at: "2025-01-28T16:00:00.000Z",
        note: "Agreed deal: rent 21,500 with waived common fee & included fiber WiFi!",
      },
    ],
    contract: {
      id: "ct-apt1",
      listing_id: "apt-1",
      start_date: "2025-03-01",
      end_date: "2026-02-28",
      duration_months: 12,
      deposit_refund_terms: "Deduction only for damages beyond fair wear and tear. Returned in 15 days.",
      pet_allowed: true,
      smoking_allowed: false,
      guest_allowed: true,
      early_termination_penalty: "1 month rent penalty with 30 days advance notice.",
      contract_file_url: "https://example.com/contracts/baan-siri-signed.pdf",
    },
    viewing_logs: [
      {
        id: "vl-apt1",
        listing_id: "apt-1",
        scheduled_at: "2025-01-25T11:00:00.000Z",
        notes: "Loved the quiet greenery. Manager was super friendly. Pet policy allows small dogs up to 10kg.",
        rating: 5.0,
        completed: true,
      },
    ],
  },
  {
    id: "dorm-1",
    name: "Samyan Smart Studio",
    address: "Rama IV Rd, Wang Mai, Pathum Wan, Bangkok 10330",
    lat: 13.7335,
    lng: 100.5284,
    type: "dorm",
    size_sqm: 28,
    floor: 6,
    view: "Samyan Mitrtown skyline",
    source_url: "https://www.renthub.in.th/samyan-smart-studio",
    contact_phone: "085-444-2211",
    contact_line: "samyan_stay",
    status: "interested",
    is_favorite: false,
    created_at: "2025-02-12T13:00:00.000Z",
    notes: "3-min walk to Chulalongkorn University and Samyan MRT. Good budget option for student or campus commute.",
    amenities: {
      elevator: true,
      gym: false,
      pool: false,
      parking: false,
      cctv: true,
      keycard: true,
    },
    photos: [
      "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&auto=format&fit=crop&q=80",
    ],
    price_history: [
      {
        id: "ph-dorm1",
        listing_id: "dorm-1",
        rent: 11000,
        deposit: 22000,
        advance: 11000,
        common_fee: 300,
        parking_fee: 500,
        internet_fee: 350,
        water_type: "metered",
        water_rate: "18 ฿/unit",
        electric_type: "metered",
        electric_rate: "8 ฿/unit",
        recorded_at: "2025-02-12T13:00:00.000Z",
      },
    ],
    viewing_logs: [],
  },
  {
    id: "condo-5",
    name: "The Base Garden Rama 9",
    address: "Rama 9 Rd, Hua Mak, Bang Kapi, Bangkok 10240",
    lat: 13.7485,
    lng: 100.6021,
    type: "condo",
    size_sqm: 31,
    floor: 9,
    view: "Unblocked canal view",
    source_url: "https://www.ddproperty.com/en/property/the-base-garden-rama-9",
    contact_phone: "083-999-7744",
    contact_line: "rama9_condo",
    status: "viewing_scheduled",
    is_favorite: false,
    created_at: "2025-02-16T17:00:00.000Z",
    notes: "Affordable modern condo by Sansiri. Shuttle bus to Airport Rail Link Ramkhamhaeng. Nice garden and pool area.",
    amenities: {
      elevator: true,
      gym: true,
      pool: true,
      parking: true,
      cctv: true,
      keycard: true,
    },
    photos: [
      "https://images.unsplash.com/photo-1567496898669-ee935f5f647a?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&auto=format&fit=crop&q=80",
    ],
    price_history: [
      {
        id: "ph-condo5",
        listing_id: "condo-5",
        rent: 13500,
        deposit: 27000,
        advance: 13500,
        common_fee: 0,
        parking_fee: 0,
        internet_fee: 0,
        water_type: "metered",
        water_rate: "18 ฿/unit",
        electric_type: "government",
        electric_rate: "MEA Official Rate",
        recorded_at: "2025-02-16T17:00:00.000Z",
      },
    ],
    viewing_logs: [
      {
        id: "vl-condo5",
        listing_id: "condo-5",
        scheduled_at: "2025-03-05T15:30:00.000Z",
        notes: "Appointment scheduled with agent Khunploy.",
        rating: 3.5,
        completed: false,
      },
    ],
  },
  {
    id: "house-1",
    name: "Sukhumvit 71 Pridi Townhome",
    address: "Pridi Banomyong Soi 26, Sukhumvit 71, Watthana, Bangkok 10110",
    lat: 13.7291,
    lng: 100.5912,
    type: "house",
    size_sqm: 140,
    floor: 3,
    view: "Private front patio & garden",
    source_url: "https://www.facebook.com/groups/bangkokexpats/posts/pridi-townhome",
    contact_phone: "081-444-9900",
    contact_line: "pridi_owner",
    status: "rejected",
    is_favorite: false,
    created_at: "2025-02-01T12:00:00.000Z",
    notes: "Huge space with 3 bedrooms, but monthly rent is above budget and requires motorcycle to get out to BTS Phra Khanong.",
    amenities: {
      elevator: false,
      gym: false,
      pool: false,
      parking: true,
      cctv: true,
      keycard: false,
    },
    photos: [
      "https://images.unsplash.com/photo-1513584684374-8bab748fbf90?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&auto=format&fit=crop&q=80",
    ],
    price_history: [
      {
        id: "ph-house1",
        listing_id: "house-1",
        rent: 32000,
        deposit: 64000,
        advance: 32000,
        common_fee: 0,
        parking_fee: 0,
        internet_fee: 700,
        water_type: "metered",
        water_rate: "Government Rate",
        electric_type: "government",
        electric_rate: "MEA Official Rate",
        recorded_at: "2025-02-01T12:00:00.000Z",
      },
    ],
    viewing_logs: [
      {
        id: "vl-house1",
        listing_id: "house-1",
        scheduled_at: "2025-02-08T10:00:00.000Z",
        notes: "Alley is too narrow for two cars to pass. No gym or pool. Decided to reject.",
        rating: 2.5,
        completed: true,
      },
    ],
  },
];
